name: phone_log
description: A new flutter plugin project.
version: 0.0.8
homepage: https://github.com/jiajiabingcheng/phone_log

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fixnum: ^1.0.1

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.jiajiabingcheng.phonelog
    pluginClass: PhoneLogPlugin

dev_dependencies:
  mockito: ^5.2.0
  flutter_test:
    sdk: flutter
