name: audiofileplayer_example
description: Demonstrates how to use the audiofileplayer plugin.
publish_to: 'none'

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^0.11.3
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  audiofileplayer:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icons/

